package com.hxzy.vo;

public class FamilyNameData {

	/* 598 百家姓 */
	public static FamilyName[] Surname= {new FamilyName("赵",1),new FamilyName("钱",3),new FamilyName("孙",1),new FamilyName("李",3),new FamilyName("周",3),new FamilyName("吴",3),new FamilyName("郑",3),new FamilyName("王",1),new FamilyName("冯",2),new FamilyName("陈",1),new FamilyName("褚",3),new FamilyName("卫",3),new FamilyName("蒋",2),new FamilyName("沈",2),new FamilyName("韩",3),new FamilyName("杨",1),new FamilyName("朱",1),new FamilyName("秦",1),new FamilyName("尤",3),new FamilyName("许",2),
			  new FamilyName("何",1),new FamilyName("吕",1),new FamilyName("施",3),new FamilyName("张",1),new FamilyName("孔",2),new FamilyName("曹",3),new FamilyName("严",3),new FamilyName("华",3),new FamilyName("金",3),new FamilyName("魏",3),new FamilyName("陶",3),new FamilyName("姜",3),new FamilyName("戚",3),new FamilyName("谢",3),new FamilyName("邹",3),new FamilyName("喻",3),new FamilyName("柏",3),new FamilyName("水",3),new FamilyName("窦",3),new FamilyName("章",3),new FamilyName("云",3),new FamilyName("苏",3),new FamilyName("潘",2),new FamilyName("葛",3),new FamilyName("奚",3),new FamilyName("范",2),new FamilyName("彭",2),new FamilyName("郎",3),
			  new FamilyName("鲁",3),new FamilyName("韦",3),new FamilyName("昌",3),new FamilyName("马",3),new FamilyName("苗",3),new FamilyName("凤",3),new FamilyName("花",3),new FamilyName("方",3),new FamilyName("俞",3),new FamilyName("任",3),new FamilyName("袁",3),new FamilyName("柳",3),new FamilyName("酆",3),new FamilyName("鲍",3),new FamilyName("史",3),new FamilyName("唐",3),new FamilyName("费",3),new FamilyName("廉",3),new FamilyName("岑",3),new FamilyName("薛",3),new FamilyName("雷",3),new FamilyName("贺",3),new FamilyName("倪",3),new FamilyName("汤",3),new FamilyName("滕",3),new FamilyName("殷",3),
			  new FamilyName("罗",1),new FamilyName("毕",3),new FamilyName("郝",3),new FamilyName("邬",3),new FamilyName("安",3),new FamilyName("常",3),new FamilyName("乐",3),new FamilyName("于",3),new FamilyName("时",3),new FamilyName("傅",3),new FamilyName("皮",3),new FamilyName("卞",3),new FamilyName("齐",3),new FamilyName("康",3),new FamilyName("伍",3),new FamilyName("余",3),new FamilyName("元",3),new FamilyName("卜",3),new FamilyName("顾",3),new FamilyName("孟",3),new FamilyName("平",3),new FamilyName("黄",3),new FamilyName("和",3),
			  new FamilyName("穆",3),new FamilyName("萧",3),new FamilyName("尹",3),new FamilyName("姚",3),new FamilyName("邵",3),new FamilyName("湛",3),new FamilyName("汪",3),new FamilyName("祁",3),new FamilyName("毛",3),new FamilyName("禹",3),new FamilyName("狄",3),new FamilyName("米",3),new FamilyName("贝",3),new FamilyName("明",3),new FamilyName("臧",3),new FamilyName("计",3),new FamilyName("伏",3),new FamilyName("成",3),new FamilyName("戴",3),new FamilyName("谈",3),new FamilyName("宋",3),new FamilyName("茅",3),new FamilyName("庞",3),new FamilyName("熊",3),new FamilyName("纪",3),new FamilyName("舒",3),
			  new FamilyName("屈",3),new FamilyName("项",3),new FamilyName("祝",2),new FamilyName("董",3),new FamilyName("梁",3),new FamilyName("杜",3),new FamilyName("阮",3),new FamilyName("蓝",3),new FamilyName("闵",3),new FamilyName("席",3),new FamilyName("季",3),new FamilyName("麻",3),new FamilyName("强",3),new FamilyName("贾",3),new FamilyName("路",3),new FamilyName("娄",3),new FamilyName("危",3),new FamilyName("江",3),new FamilyName("童",3),new FamilyName("颜",3),new FamilyName("郭",3),new FamilyName("梅",3),new FamilyName("盛",3),new FamilyName("林",3),new FamilyName("刁",3),new FamilyName("钟",3),
			  new FamilyName("徐",2),new FamilyName("邱",2),new FamilyName("骆",3),new FamilyName("高",3),new FamilyName("夏",3),new FamilyName("蔡",3),new FamilyName("田",3),new FamilyName("樊",3),new FamilyName("胡",3),new FamilyName("凌",3),new FamilyName("霍",3),new FamilyName("虞",3),new FamilyName("万",3),new FamilyName("支",3),new FamilyName("柯",3),new FamilyName("昝",3),new FamilyName("管",3),new FamilyName("卢",3),new FamilyName("莫",3),new FamilyName("经",3),new FamilyName("房",3),new FamilyName("裘",3),new FamilyName("缪",3),new FamilyName("干",3),new FamilyName("解",3),new FamilyName("应",3),
			  new FamilyName("宗",3),new FamilyName("丁",3),new FamilyName("宣",3),new FamilyName("贲",3),new FamilyName("邓",3),new FamilyName("郁",3),new FamilyName("单",3),new FamilyName("杭",3),new FamilyName("洪",3),new FamilyName("包",3),new FamilyName("诸",3),new FamilyName("左",3),new FamilyName("石",3),new FamilyName("崔",3),new FamilyName("吉",3),new FamilyName("钮",3),new FamilyName("龚",3),new FamilyName("程",3),new FamilyName("嵇",3),new FamilyName("邢",3),new FamilyName("滑",3),new FamilyName("裴",3),new FamilyName("陆",3),new FamilyName("荣",3),new FamilyName("翁",3),new FamilyName("荀",3),
			  new FamilyName("羊",3),new FamilyName("于",3),new FamilyName("惠",3),new FamilyName("甄",3),new FamilyName("曲",3),new FamilyName("家",3),new FamilyName("封",3),new FamilyName("芮",3),new FamilyName("羿",3),new FamilyName("储",3),new FamilyName("靳",3),new FamilyName("汲",3),new FamilyName("邴",3),new FamilyName("糜",3),new FamilyName("松",3),new FamilyName("井",3),new FamilyName("段",3),new FamilyName("富",3),new FamilyName("巫",3),new FamilyName("乌",3),new FamilyName("焦",3),new FamilyName("巴",3),new FamilyName("弓",3),new FamilyName("牧",3),new FamilyName("隗",3),new FamilyName("山",3),
			  new FamilyName("谷",3),new FamilyName("车",3),new FamilyName("侯",3),new FamilyName("宓",3),new FamilyName("蓬",3),new FamilyName("全",3),new FamilyName("郗",3),new FamilyName("班",3),new FamilyName("仰",3),new FamilyName("秋",3),new FamilyName("仲",3),new FamilyName("伊",3),new FamilyName("宫",3),new FamilyName("宁",3),new FamilyName("仇",3),new FamilyName("栾",3),new FamilyName("暴",3),new FamilyName("甘",3),new FamilyName("钭",3),new FamilyName("厉",3),new FamilyName("戎",3),new FamilyName("祖",3),new FamilyName("武",3),new FamilyName("符",3),new FamilyName("刘",3),new FamilyName("景",3),
			  new FamilyName("詹",3),new FamilyName("束",3),new FamilyName("龙",3),new FamilyName("叶",3),new FamilyName("幸",3),new FamilyName("司",3),new FamilyName("韶",3),new FamilyName("郜",3),new FamilyName("黎",3),new FamilyName("蓟",3),new FamilyName("溥",3),new FamilyName("印",3),new FamilyName("宿",3),new FamilyName("白",3),new FamilyName("怀",3),new FamilyName("蒲",3),new FamilyName("邰",3),new FamilyName("从",3),new FamilyName("鄂",3),new FamilyName("索",3),new FamilyName("咸",3),new FamilyName("籍",3),new FamilyName("赖",3),new FamilyName("卓",3),new FamilyName("蔺",3),new FamilyName("屠",3),
			  new FamilyName("蒙",3),new FamilyName("池",3),new FamilyName("乔",3),new FamilyName("阴",3),new FamilyName("郁",3),new FamilyName("胥",3),new FamilyName("能",3),new FamilyName("苍",3),new FamilyName("双",3),new FamilyName("闻",3),new FamilyName("莘",3),new FamilyName("党",3),new FamilyName("翟",3),new FamilyName("谭",3),new FamilyName("贡",3),new FamilyName("劳",3),new FamilyName("逄",3),new FamilyName("姬",3),new FamilyName("申",3),new FamilyName("扶",3),new FamilyName("堵",3),new FamilyName("冉",3),new FamilyName("宰",3),new FamilyName("郦",3),new FamilyName("雍",3),new FamilyName("却",3),
			  new FamilyName("璩",3),new FamilyName("桑",3),new FamilyName("桂",3),new FamilyName("濮",3),new FamilyName("牛",3),new FamilyName("寿",3),new FamilyName("通",3),new FamilyName("边",3),new FamilyName("扈",3),new FamilyName("燕",3),new FamilyName("冀",3),new FamilyName("浦",3),new FamilyName("尚",3),new FamilyName("农",3),new FamilyName("温",3),new FamilyName("别",3),new FamilyName("庄",3),new FamilyName("晏",3),new FamilyName("柴",3),new FamilyName("瞿",3),new FamilyName("阎",3),new FamilyName("充",3),new FamilyName("慕",3),new FamilyName("连",3),new FamilyName("茹",3),new FamilyName("习",3),
			  new FamilyName("宦",3),new FamilyName("艾",3),new FamilyName("鱼",3),new FamilyName("容",3),new FamilyName("向",3),new FamilyName("古",3),new FamilyName("易",3),new FamilyName("慎",3),new FamilyName("戈",3),new FamilyName("廖",3),new FamilyName("庾",3),new FamilyName("终",3),new FamilyName("暨",3),new FamilyName("居",3),new FamilyName("衡",3),new FamilyName("步",3),new FamilyName("都",3),new FamilyName("耿",3),new FamilyName("满",3),new FamilyName("弘",3),new FamilyName("匡",3),new FamilyName("国",3),new FamilyName("文",3),new FamilyName("寇",3),new FamilyName("广",3),new FamilyName("禄",3),
			  new FamilyName("阙",3),new FamilyName("东",3),new FamilyName("欧",3),new FamilyName("殳",3),new FamilyName("沃",3),new FamilyName("利",3),new FamilyName("蔚",3),new FamilyName("越",3),new FamilyName("夔",3),new FamilyName("隆",3),new FamilyName("师",3),new FamilyName("巩",3),new FamilyName("厍",3),new FamilyName("聂",3),new FamilyName("晁",3),new FamilyName("勾",3),new FamilyName("敖",3),new FamilyName("融",3),new FamilyName("冷",3),new FamilyName("訾",3),new FamilyName("辛",3),new FamilyName("阚",3),new FamilyName("那",3),new FamilyName("简",3),new FamilyName("饶",3),new FamilyName("空",3),
			  new FamilyName("曾",3),new FamilyName("毋",3),new FamilyName("沙",3),new FamilyName("乜",3),new FamilyName("养",3),new FamilyName("鞠",3),new FamilyName("须",3),new FamilyName("丰",3),new FamilyName("巢",3),new FamilyName("关",3),new FamilyName("蒯",3),new FamilyName("相",3),new FamilyName("查",3),new FamilyName("后",3),new FamilyName("荆",3),new FamilyName("红",3),new FamilyName("游",3),new FamilyName("郏",3),new FamilyName("竺",3),new FamilyName("权",3),new FamilyName("逯",3),new FamilyName("盖",3),new FamilyName("益",3),new FamilyName("桓",3),new FamilyName("公",3),new FamilyName("仉",3),
			  new FamilyName("督",3),new FamilyName("岳",3),new FamilyName("帅",3),new FamilyName("缑",3),new FamilyName("亢",3),new FamilyName("况",3),new FamilyName("郈",3),new FamilyName("有",3),new FamilyName("琴",3),new FamilyName("归",3),new FamilyName("海",3),new FamilyName("晋",3),new FamilyName("楚",3),new FamilyName("闫",3),new FamilyName("法",3),new FamilyName("汝",3),new FamilyName("鄢",3),new FamilyName("涂",3),new FamilyName("钦",3),new FamilyName("商",3),new FamilyName("牟",3),new FamilyName("佘",3),new FamilyName("佴",3),new FamilyName("伯",3),new FamilyName("赏",3),new FamilyName("墨",3),
			  new FamilyName("哈",3),new FamilyName("谯",3),new FamilyName("篁",3),new FamilyName("年",3),new FamilyName("爱",3),new FamilyName("阳",3),new FamilyName("佟",3),new FamilyName("言",3),new FamilyName("福",3),new FamilyName("南",3),new FamilyName("火",3),new FamilyName("铁",3),new FamilyName("迟",3),new FamilyName("漆",3),new FamilyName("官",3),new FamilyName("冼",3),new FamilyName("真",3),new FamilyName("展",3),new FamilyName("繁",3),new FamilyName("檀",3),new FamilyName("祭",3),new FamilyName("密",3),new FamilyName("敬",3),new FamilyName("揭",3),new FamilyName("舜",3),new FamilyName("楼",3),
			  new FamilyName("疏",3),new FamilyName("冒",3),new FamilyName("浑",3),new FamilyName("挚",3),new FamilyName("胶",3),new FamilyName("随",3),new FamilyName("高",3),new FamilyName("皋",3),new FamilyName("原",3),new FamilyName("种",3),new FamilyName("练",3),new FamilyName("弥",3),new FamilyName("仓",3),new FamilyName("眭",3),new FamilyName("蹇",3),new FamilyName("覃",3),new FamilyName("阿",3),new FamilyName("门",3),new FamilyName("恽",3),new FamilyName("来",3),new FamilyName("綦",3),new FamilyName("召",3),new FamilyName("仪",3),new FamilyName("风",3),new FamilyName("介",3),new FamilyName("巨",3),
			  new FamilyName("木",3),new FamilyName("京",3),new FamilyName("狐",3),new FamilyName("郇",3),new FamilyName("虎",3),new FamilyName("枚",3),new FamilyName("抗",3),new FamilyName("达",3),new FamilyName("杞",3),new FamilyName("苌",3),new FamilyName("折",3),new FamilyName("麦",3),new FamilyName("庆",3),new FamilyName("过",3),new FamilyName("竹",3),new FamilyName("端",3),new FamilyName("鲜",3),new FamilyName("皇",3),new FamilyName("亓",3),new FamilyName("老",3),new FamilyName("是",3),new FamilyName("秘",3),new FamilyName("畅",3),new FamilyName("邝",3),new FamilyName("还",3),new FamilyName("宾",3),
			  new FamilyName("闾",3),new FamilyName("辜",3),new FamilyName("纵",3),new FamilyName("侴",3),new FamilyName("万俟",3),new FamilyName("司马",3),new FamilyName("上官",3),new FamilyName("欧阳",3),new FamilyName("夏侯",3),new FamilyName("诸葛",3),new FamilyName("闻人",3),new FamilyName("东方",3),new FamilyName("赫连",3),new FamilyName("皇甫",3),new FamilyName("羊舌",3),new FamilyName("尉迟",3),new FamilyName("公羊",3),new FamilyName("澹台",3),new FamilyName("公冶",3),new FamilyName("宗正",3),
			  new FamilyName("濮阳",3),new FamilyName("淳于",3),new FamilyName("单于",3),new FamilyName("太叔",3),new FamilyName("申屠",3),new FamilyName("公孙",3),new FamilyName("仲孙",3),new FamilyName("轩辕",3),new FamilyName("令狐",3),new FamilyName("钟离",3),new FamilyName("宇文",3),new FamilyName("长孙",3),new FamilyName("慕容",3),new FamilyName("鲜于",3),new FamilyName("闾丘",3),new FamilyName("司徒",3),new FamilyName("司空",3),new FamilyName("兀官",3),new FamilyName("司寇",3),
			  new FamilyName("南门",3),new FamilyName("呼延",3),new FamilyName("子车",3),new FamilyName("颛孙",3),new FamilyName("端木",3),new FamilyName("巫马",3),new FamilyName("公西",3),new FamilyName("漆雕",3),new FamilyName("车正",3),new FamilyName("壤驷",3),new FamilyName("公良",3),new FamilyName("拓跋",3),new FamilyName("夹谷",3),new FamilyName("宰父",3),new FamilyName("谷梁",3),new FamilyName("段干",3),new FamilyName("百里",3),new FamilyName("东郭",3),new FamilyName("微生",3),
			  new FamilyName("梁丘",3),new FamilyName("左丘",3),new FamilyName("东门",3),new FamilyName("西门",3),new FamilyName("南宫",3),new FamilyName("第五",3),new FamilyName("公仪",3),new FamilyName("公乘",3),new FamilyName("太史",3),new FamilyName("仲长",3),new FamilyName("叔孙",3),new FamilyName("屈突",3),new FamilyName("尔朱",3),new FamilyName("东乡",3),new FamilyName("相里",3),new FamilyName("胡母",3),new FamilyName("司城",3),new FamilyName("张廖",3),new FamilyName("雍门",3),
			  new FamilyName("毋丘",3),new FamilyName("贺兰",3),new FamilyName("綦毋",3),new FamilyName("屋庐",3),new FamilyName("独孤",3),new FamilyName("南郭",3),new FamilyName("北宫",3),new FamilyName("王孙",3)};

}
